"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_1 = require("inversify");
require("reflect-metadata");
var irc_socket_1 = require("./irc-socket");
var respond_to_ping_1 = require("./behaviours/respond-to-ping");
var log_data_1 = require("./behaviours/log-data");
var urmum_1 = require("./behaviours/urmum");
var bot_parser_1 = require("./bot-parser");
var repeat_mention_1 = require("./behaviours/repeat-mention");
var counter_1 = require("./behaviours/counter");
var stdin_1 = require("./stdin");
var irc_parser_1 = require("./irc-parser");
exports.AppContainer = new inversify_1.Container({ defaultScope: "Singleton", autoBindInjectable: true });
exports.AppContainer.get(irc_socket_1.IRCSocket);
exports.AppContainer.get(bot_parser_1.BotParser);
exports.AppContainer.get(irc_parser_1.IRCParser);
exports.AppContainer.get(stdin_1.Stdin);
exports.AppContainer.get(respond_to_ping_1.RespondToPing);
exports.AppContainer.get(log_data_1.LogData);
exports.AppContainer.get(urmum_1.UrMum);
exports.AppContainer.get(counter_1.Counter);
exports.AppContainer.get(repeat_mention_1.RepeatMention);
